package proj1;
import java.util.Scanner;
public class Main {
	public static void main(String[] args) {
		AVL avl=new AVL();
		Scanner sc=new Scanner(System.in);
		avl.create("brb","Be right back");
		avl.create("btw","By the way");
		avl.create("ama", "Ask Me Anything");			
		avl.create("lmk","Let me know");
		avl.create("gtg","Got to go");
		avl.create("dm", "Direct Message");
		avl.create("idk", "I don't know");
		avl.create("rofl","Rolling on floor laughing");
		avl.create("stfu", "Shut the *swear word!* up");
		avl.create("icymi", "In case you missed it");
		avl.create("tl","Too long" );
		avl.create("ikr", "I know right");
		avl.create("dr", "Didn’t read");
		avl.create("nvm", "Nevermind");
		avl.create("tgif","Thank goodness it’s Friday");
		avl.create("tbh","To be honest");
		avl.create("tbf", "To be frank");
		avl.create("rn", "Right now");
		avl.create("qotd","Quote of the day");
		avl.create("ootd","Outfit of the day");
		avl.create("lol","Laugh out loud");
		avl.create("ttyl", "Talk to you later");
		avl.create("hit me up"," Hit me up");
		avl.create("fwiw", "For what it’s worth");
		avl.create("imo", "In my opinion");
		avl.create("imho", "In my humble opinion");
		avl.create("tba", "To be announced");
		avl.create("tbd", "To be decided");
		avl.create("ae","Accident & Emergency");
        avl.create("af","Always And Forever");
        avl.create("afe","Abercrombie & Fitch");
        avl.create("ar","Artists & Repertoire");
        avl.create("an","Author's Note");
        avl.create("aw","Anyway");
        avl.create("a1","Top quality");
        avl.create("a2dp","Advanced Audio Distribution Profile");
        avl.create("a3","Anywhere, Any time, Any place");
        avl.create("a4u","All For You");
        avl.create("a7a","Frustration, anger (Arabic)");
        avl.create("a7x","Avenged Sevenfold (band)");
        avl.create("aa","Alcoholics Anonymous");
        avl.create("aab","Average At Best");
        avl.create("aac","Apple Audio Compression");
        avl.create("aak","Alive And Kicking");
        avl.create("aamof","As A Matter Of Fact");
        avl.create("aap","Always A Pleasure");
        avl.create("aar","At Any Rate");
        avl.create("aarp","American Association of Retired Persons");
        avl.create("aat","And Another Thing");
        avl.create("aawy","And Also With You");
        avl.create("aayf","As Always, Your Friend");
        avl.create("abbo","Accountants Bookkeepers and Business Owners");
        avl.create("e","Ecstasy");
        avl.create("eoe","Errors and omissions excluded");
        avl.create("ecig","Electronic Cigarett");
        avl.create("edating","Online dating");
        avl.create("evite","Electronic Invitation");
        avl.create("ev","Everyone");
        avl.create("eeg","Ear To Ear Grin");
        avl.create("ea","Electronic Arts");
        avl.create("eas","End of Active Service");
        avl.create("eb","Eyeball");
        avl.create("ebcak","Error Between Chair And Keyboard");
        avl.create("ebd","End of Business Day");
        avl.create("ebm","Electronic Body Music");
        avl.create("ebony","Dark skin tone");
        avl.create("ebt","Electronic Benefits Transfer");
        avl.create("ecg","Electrocardiogram");
        avl.create("eco","Ecological");
        avl.create("ect","Misspelling of 'etc'");
        avl.create("ecu","Electronic Control Unit");
        avl.create("ecw","Extreme Championship Wrestling");
        avl.create("edc","Every Day Carry");
        avl.create("edd","Estimated Delivery Date");
        avl.create("eddress	","Email address");
        avl.create("edgy","Cutting edge");
        avl.create("edith","Even Dead, I'm The Hero");
        avl.create("ial","I Ain't Laughing");
        avl.create("ialto","I Always Love That One");
        avl.create("iama","I Am Mildly Amused");
        avl.create("ianand","I Am Not A Doctor");
        avl.create("ianal","I Am Not A Lawyer (this is an uninformed opinion)");
        avl.create("iakrt","I already know that");
        avl.create("ias","In A Second");
        avl.create("iatco","I Am The Cool One");
        avl.create("iau","I Adore You");
        avl.create("iaw","In Accordance With");
        avl.create ("iawtc","I Agree With That/This Comment");
        avl.create("iawtcsm	","I Agree With This Comment So Much");
        avl.create("iawtp","I Agree With This Post");
        avl.create("o","Ounce (of drugs)");
        avl.create("orly","Oh, Really?");
        avl.create("oo","Over and Out");
        avl.create("oa","Over Acting");
        avl.create("oan","On Another Note");
        avl.create("oao","Over And Out");
        avl.create("oap","Old Age Pensioner");
        avl.create("oatus","On A Totally Unrelated Subject");
        avl.create("oaus","On An Unrelated Subject");
        avl.create("ob","Oh, Brother");
        avl.create("obby","Oh, Baby");
        avl.create("obe","Overcome By Events");
        avl.create("obgyn","Gynecologist (OBstetrics and GYNecology)");
        avl.create("obhwf","One Big Happy Weasely Family");
        avl.create("obo","Or Best Offer");
        avl.create("obq","Oh, Be Quiet");
        avl.create("obs","Obviously");
        avl.create("obtw","Oh, By The Way");
        avl.create("obv","Obviously");
        avl.create("obx","Outer Banks North Carolina");
        avl.create("oc","Of Course");
        avl.create("ocd","Obsessive Compulsive Disorder");
        avl.create("och","Oh (Scottish)");
        avl.create("ocn","Of Course Not");
        avl.create("oco","Oh, Come On");
        avl.create("ocr","Optical Character Recognition");
        avl.create("oct","On Company Time");
        avl.create("od","Overdose");
        avl.create("lit", "When something is very good" );  
        avl.create("extra","Dramatic");
        avl.create("salty","When someone is upset"); 
        avl.create("flex","Someone is showing off");
        avl.create("highkey","Liked something secretly");
        avl.create("shook","They are shocked or incredibly surprised");
        avl.create("spilling the tea","They are gossiping");
        avl.create("wallflower","A shy person");
        avl.create("busted ","Getting caught");
        avl.create("g2g","Got to go");
        avl.create("lurker","When someone visits a forum often");
        avl.create("faq","Frequently asked questions");
        avl.create("pwned","Defeated or humiliated");
        avl.create("lag","When computer application is slow");
        avl.create("noob","When someone is new to something");
        avl.create("photobomb","When someone or something appears in a photo unexpectedly");
        avl.create("spam","Type of email which is not meaningful");
        avl.create("trending","Popular or fashionable at a moment");
        avl.create("handle ","Nickname for a website");
        avl.create("haha","Laughter");
        avl.create("irl","In real life");
        avl.create("nsfw","Not safe for work");
        avl.create("dr","Didn't read");
        avl.create("otl","Emoji used to show an expression or feeling");
        avl.create("wack"," Bad ,wrong ,worthless");
        avl.create("wacko","Crazy, insane.");
        avl.create("wacky","Crazy, zany.");
        avl.create("wad",	"(Noun) A large amount of money.");
        avl.create("nab", "To catch someone doing something wrong.");
        avl.create("nail","To do something perfectly.");
        avl.create("narc","A narcotics officer, a police officer working in drug trade suppression.");
        avl.create("nark","A police officer working in drug trade suppression.");
        avl.create("neat","Very good, excellent.");
        avl.create("nerd","A studious person with few social skills.");
        avl.create("ocker","A crude and obnoxious Australian.");
        avl.create("od","To take an overdose of a drug.");
        avl.create("oddball","A strange or eccentric person  ");
        avl.create("off","To murder, to kill.");
        avl.create("off the hook","No longer suspected of guilt ");
        avl.create("pack heat","To carry a gun.");
        avl.create("pack it in","To stop what you're doing, to quit.");
        avl.create("pain in the arse","Someone or something that's annoying or troublesome.");
        avl.create("pain in the ass","An annoying or troublesome person or thing.");
        avl.create("pal","A friend.");
        avl.create("quick sticks","Quickly. ");
        avl.create("quid","One pound sterling.");
        avl.create("quids-in","In profit. ");
        avl.create("quilt","A feeble or pathetic person. ");  
        avl.create("quack","doctor");
        avl.create("laa","Lad");
        avl.create("labtop","Laptop");
        avl.create("lacking","Without a weapon, specifically a gun");
        avl.create("lad","Guy");
        avl.create("maab","Male-Assigned At Birth");
        avl.create("mac","Media Access Control");
        avl.create("maching","Going at maximum Speed (skiing or biking)");
        avl.create("mack","Flirt");
        avl.create("mad","Really, extremely");
        avl.create("madd","Mothers Against Drunk Driving");
        avl.create("mag","Magazine");
        avl.create("jaja","Spanish laugh");
        avl.create("b","Bro");
        avl.create("ban","Banned");
        
        avl.create("bb","Baby");
        avl.create("bd","Bondage And Discipline");
      
        avl.create("be","Breaking And Entering");
        avl.create("C","Very happy");
        avl.create("caac","Cool As A Cucumber");
        avl.create("cab","Misspelling of CBA");
        avl.create("cachai","Do you understand?");
        avl.create("cache","Store for temporary computer files");
        avl.create("cactus","Broken, dead");
        avl.create("dada","Defence Against the Dark Arts (Harry Potter)");
        avl.create("dadt","Don't Ask, Don't Tell");
        avl.create("dae","Does Anybody Else");
        avl.create("dag","Damn");
       
        avl.create("daggy","Uncool, not trendy, untidy");
        avl.create ("faa","Federal Aviation Administration)");
        		
        avl.create( "faab","Female-Assigned At Birth");
        avl.create("faak","Falling Asleep At Keyboard");
        avl.create ("fab","Fabulous");
        avl.create("fabu","Fabulous");
        avl.create("ga	","Go Ahead");
        avl.create("gac","Guilty As Charged");
      
        avl.create("gaff","House");
        avl.create("gafaia","Get Away From It All");
        avl.create("gafm","Get Away From Me");
        avl.create("gag","About to throw up");
        avl.create("gl","Good luck");
        avl.create("gg","Good game");
        avl.create("glhf","Good luck have fun");
        avl.create("hf","Have fun");
        
        
        avl.create("ha","Sarcastic laugh");
        avl.create("habbo","Online community/game");
        avl.create("habibi","My darling (Arabic)");
        avl.create("hac","Asian Chick");
        avl.create("hacer","Hacker");
        avl.create("jaf","Just A Friend");
        
        avl.create("jag","Socially inept person");
        avl.create("jah","God,Jehovah");
        avl.create("jailbreak","Crack an iPhone");
        avl.create("kd","Kraft Dinner");
        avl.create("kda","Kills / Deaths / Assists");
        avl.create("kdr","Kill/Death Ratio");
        avl.create("keed","Kid, joke");
        avl.create("keel","Kill");
        avl.create("lsa","Cantonese Exclamation");
        
        avl.create ("ump","Umpire.");
        avl.create ("umpteen","Many, countless.");
        avl.create ("uncle sam","The U.S.A., the U.S. government.");
        avl.create ("uncool.","Not good, not acceptable, not fashionable.");
        avl.create  ("uac","User Account Control");
        avl.create  ("uae",	"United Arab Emirates");
        avl.create ("uak","You Already Know");
        avl.create  ("uan","Universal Access Number");
        avl.create ("uark","You Already Know");
        avl.create  ("uav","Urban Assault Vehicle");
        avl.create("ub","You biggit");
        avl.create  ("ubt","You Be Too");
        avl.create ("ubber","Uber, very");
        avl.create  ("ubd","User Brain Damage");
        avl.create ("v","Black−American slang for an unfriendly female");
        avl.create ("v.a.t.","British slang for vodka and tonic.");
        avl.create ("v.c.","American slang for Viet Cong, a north Vietnamese combatant.");
        avl.create ("vac","British slang for a university or other higher education holiday.");
        avl.create ("vacuum cleaner","Black−American slang for ones lungs");
        avl.create("zilchNothing","Zero");
        avl.create("zibi","Person from Zimbabwe");
        avl.create("zing","Owned");

        avl.create("zip","Ounce of marijauna");
        avl.create ("zit","Spot, pimple");
        avl.create("zoinks","jeepers");
        avl.create("yacc","Yet Another Compiler-Compiler");
        avl.create("yam","And so on, blah");
        avl.create("yagb","You Ain't Grizz Baby (COD)");
        avl.create("yahoo","Yob, lout");
        avl.create("yahwej","The name of God in hebrew");
        avl.create("yak","You Already Know");

        
		int ch;
		do{
			System.out.println("**************************** Menu ********************************");
			System.out.println("1.Find a Word");
			System.out.println("2.Display all words");
			System.out.println("3.Exit");
			System.out.println("******************************************************************");
			System.out.print("Enter your choice : ");
			ch=sc.nextInt();
			switch(ch)
			{
			case 1:
				
				avl.findWord(); 
			break;
	
			case 2:
				avl.display(avl.getRoot());
				break;
			
			case 3: System.out.println("Program ended"); 
			break;
		}
			} while(ch != 3);

	}
}
